-- ============================================================
-- H2O 导航页 - Supabase 数据库建表 SQL & RLS 策略
-- ============================================================

-- 1. 建表
create table if not exists navigation (
  id            bigint generated by default as identity primary key,
  device_id     text not null,
  data          jsonb not null default '{}'::jsonb,
  share_code    text unique,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  unique(device_id)
);

-- 2. 索引
create index if not exists idx_navigation_device_id on navigation(device_id);
create index if not exists idx_navigation_share_code on navigation(share_code);

-- 3. 启用 RLS
alter table navigation enable row level security;

-- 4. RLS 策略：允许所有人读取（通过 device_id 或 share_code）
create policy "允许通过 device_id 读取自己的数据"
  on navigation
  for select
  using (true);

-- 5. RLS 策略：允许通过 device_id 插入/更新自己的数据
create policy "允许通过 device_id 插入数据"
  on navigation
  for insert
  with check (true);

create policy "允许通过 device_id 更新自己的数据"
  on navigation
  for update
  using (true)
  with check (true);

-- 6. RLS 策略：允许删除自己的数据
create policy "允许通过 device_id 删除自己的数据"
  on navigation
  for delete
  using (true);

-- 7. 自动更新 updated_at 触发器
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_updated_at
  before update on navigation
  for each row
  execute function update_updated_at_column();
